# -*- coding: utf-8 -*-
"""baza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yIDctFVy0SeRTLjx6dhPs_puMorGUZa
"""

import streamlit as st
import pandas as pd
from supabase import create_client, Client

st.set_page_config(page_title="Magazyn Supabase", page_icon="📦")

st.title("📦 Magazyn z bazą danych w Supabase (2 tabele)")

# ---------------------------------------------------------
# 1. Połączenie z Supabase (dane w Streamlit Secrets)
# ---------------------------------------------------------
url = st.secrets["supabase"]["url"]
key = st.secrets["supabase"]["key"]
supabase: Client = create_client(url, key)

# ---------------------------------------------------------
# 2. Formularz dodawania kategorii
# ---------------------------------------------------------
st.header("➕ Dodaj kategorię")

nazwa_kategorii = st.text_input("Nazwa kategorii:")

if st.button("Dodaj kategorię"):
    if nazwa_kategorii.strip():
        supabase.table("kategorie").insert({"nazwa": nazwa_kategorii}).execute()
        st.success(f"Dodano kategorię: {nazwa_kategorii}")
    else:
        st.error("Podaj nazwę kategorii!")

# Pobieranie listy kategorii
kat_response = supabase.table("kategorie").select("*").execute().data
df_kat = pd.DataFrame(kat_response) if kat_response else pd.DataFrame()

st.subheader("📋 Lista kategorii")
st.dataframe(df_kat)

# ---------------------------------------------------------
# 3. Formularz dodawania produktów
# ---------------------------------------------------------
st.header("➕ Dodaj produkt")

nazwa_prod = st.text_input("Nazwa produktu:")
liczba = st.number_input("Liczba:", min_value=0, step=1)
cena = st.number_input("Cena:", min_value=0.0, step=0.10)

# słownik: nazwa kategorii → id
lista_kategorii = {row["nazwa"]: row["id"] for row in kat_response} if kat_response else {}
wybor_kat = st.selectbox("Kategoria:", list(lista_kategorii.keys()) if lista_kategorii else ["Brak kategorii"])

if st.button("Dodaj produkt"):
    if not lista_kategorii:
        st.error("Najpierw dodaj kategorię!")
    else:
        supabase.table("produkty").insert({
            "nazwa": nazwa_prod,
            "liczba": liczba,
            "cena": cena,
            "kategoria_id": lista_kategorii[wybor_kat]
        }).execute()
        st.success(f"Dodano produkt: {nazwa_prod}")

# ---------------------------------------------------------
# 4. Wyświetlanie produktów
# ---------------------------------------------------------
st.header("📦 Lista produktów")

prod_response = supabase.table("produkty").select("*").execute().data
df_prod = pd.DataFrame(prod_response) if prod_response else pd.DataFrame()

st.dataframe(df_prod)

# ---------------------------------------------------------
# 5. JOIN – Produkty z kategoriami
# ---------------------------------------------------------
st.header("🔗 Produkty z kategoriami (JOIN)")

if not df_kat.empty and not df_prod.empty:
    df_join = df_prod.merge(
        df_kat,
        left_on="kategoria_id",
        right_on="id",
        suffixes=("_prod", "_kat")
    )

    df_join = df_join[["nazwa_prod", "liczba", "cena", "nazwa_kat"]]
    df_join.columns = ["Produkt", "Liczba", "Cena", "Kategoria"]

    st.dataframe(df_join)
else:
    st.info("Nie ma danych do połączenia.")
